# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
inhibit_all_warnings!

target 'CRHelper' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod "SDWebImage"
pod "Alamofire"
pod "AlamofireNetworkActivityIndicator"
pod "pop"
pod "SVProgressHUD"
pod "YYModel"
pod "SCTableIndex"
pod 'MLeaksFinder'
pod 'DLSlideView', :git => 'https://github.com/agdsdl/DLSlideView.git'

end
